---
title: "TP_ANOVA_1"
output: html_notebook
---

$\underline{EXERCICE}$ $1$

```{r}
# Création de vecteur Y
x1=c(2,rep(6,2),rep(11,2),12,10,15,7,5)
x2=c(rep(13,2),15,rep(14,2),17,rep(16,2),4,19)
x3=c(rep(13,3),rep(17,2),10,rep(15,2),12,20)
y=c(x1,x2,x3)
# Création du facteur X
x=c(rep("A",10),rep("B",10),rep("C",10))
# X transformé en caractère qualitatif
x=as.factor(x)
```

```{r}
# Le modèle ANOVA
anova=aov(y~x)
summary(anova)
```

```{r}
# Estimation des paramètres
FactoMineR::AovSum(anova)
```

*Ainsi,*

-   $\hat{\mu}=12.36667$,
-   $\hat{\alpha_1}=-3.86667$,
-   $\hat{\alpha_2}=1.73333$,
-   $\hat{\alpha_3}=2.13333$,
-   $\hat{\sigma}^{2}=13.32963$.

```{r}
# Détecter les groupes
plot(TukeyHSD(anova,"x"))
```

*D'après le graphe du test de Tuckey, il n'y a pas de différence significative entre les classes B et C.*

*Cependant, il y a une différence significative entre les classes A et B, aussi entre les classes A et C.*

$\underline{EXERCICE}$ $2$
